#!/usr/bin/env bash

# SPDX-License-Identifier: AGPL-3.0-or-later

#    ----------------------------------------------------------------------
#    Copyright © 2024, 2025  Pellegrino Prevete
#
#    All rights reserved
#    ----------------------------------------------------------------------
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

_bin="$( \
  dirname \
    "$( \
      command \
        -v \
	  "env")")"
_lib="${_bin}/../lib"
source \
  "${_lib}/libcrash-bash/crash-bash"

# shellcheck disable=SC2034
_global_variables() {
  receive_date=""
  ks_address=""
  ks_version=""
  deployments_dir=""
  user_level=""
  wallet_name=""
  wallet_path=""
  wallet_password=""
  wallet_seed=""
  wallet_address=""
  target_network=""
  api_key=""
  cache_dir=""
  gnupg_home=""
  input_type=""
  key_import=""
  target_publisher=""
  target_address=""
  target_key=""
  key_fingerprint=""
  key_import=""
  output_prefix=""
  command_args=()
  color=""
  quiet=""
}

_requirements() {
  _check_cmd \
    'evm-chains-explorers'
  _check_cmd \
    'evm-chains-info'
  _check_cmd \
    'evm-contract-call' \
    'evm-contracts-tools'
  _check_cmd \
    'evm-contract-deployment-address' \
    'evm-contracts-tools'
  _check_cmd \
    'evm-contract-deployment-versions' \
    'evm-contracts-tools'
  _check_cmd \
    'evm-contract-deployments-dir' \
    'evm-contracts-tools'
  _check_cmd \
    'evm-wallet'
  _check_cmd \
    'evmfs'
  _check_cmd \
    'gpg-key-info'
  _check_cmd \
    'gpg' \
    'gnupg'
}

_get_conf_dir_path() {
  local \
    _dir
  _dir="${HOME}/.config/evm-openpgp-keyserver"
  echo \
    "${_dir}"
}

_cache_dir_auto_detect() {
  local \
    _dir
  _dir="${HOME}/.cache/evm-openpgp-keyserver"
  echo \
    "${_dir}"
}

_opts_setup() {
  local \
    _msg=() \
    _credentials_opts=()
  if [[ "${quiet}" == "n" ]]; then
    _evmfs_opts+=(
      -v
    )
  fi
  _credentials_opts+=(
    -N
      "${_wallet_name}"
    -k
      "${_api_key_path}"
    -w
      "${_wallet_path}"
    -s
      "${_wallet_seed}"
    -p
      "${_wallet_password}"
  )
  _evm_contract_call_opts+=(
    "${_credentials_opts[@]}"
    -n
      "${_target_network}"
    -A
      "${_abi}"
    -B
      "${_bytecode}"
    -C
      "${_compiler_output}"
    -t
      "static"
  )
  _evmfs_opts+=(
    "${_credentials_opts[@]}"
    -n
      "${_target_network}"
  )
  _keys_amount_call_opts+=(
    "${_evm_contract_call_opts[@]}"
  )
  _uri_get_call_opts+=(
    "${_evm_contract_call_opts[@]}"
  )
  _msg=(
    "evm-contract-call will be called"
    "with base options '${_evm_contract_call_opts[*]}'"
  )
  _msg_info \
    "${_msg[*]}"
}

_key_download() {
  local \
    _uri="${1}" \
    _output_file="${2}" \
    _get_opts=()
  _get_opts+=(
    "${_evmfs_opts[@]}"
    -o
      "${_output_file}"
  )
  _msg=(
    "downloading in '${_output_file}' the key"
    "at URI '${_uri}'."
  )
  _msg_info \
    "${_msg[*]}"
  evmfs \
    "${_get_opts[@]}" \
    get \
      "${_uri}"
}

_keys_amount_get() {
  evm-contract-call \
    "${_keys_amount_call_opts[@]}" \
    "${_ks_address}" \
    "keyNo" \
    "${_address}" \
    "${_publisher}"
}

_uri_key_get() {
  local \
    _key="${1}"
  evm-contract-call \
    "${_uri_get_call_opts[@]}" \
    "${_ks_address}" \
    "readKey" \
    "${_address}" \
    "${_publisher}" \
    "${_key}"
}

_key_fingerprint_get() {
  local \
    _fingerprint="${1}"
  evm-contract-call \
    "${_uri_get_call_opts[@]}" \
    "${_ks_address}" \
    "readKeyFingerprint" \
    "${_address}" \
    "${_publisher}" \
    "${_fingerprint}"
}

_keys_receive() {
  local \
    _target_network="${1}" \
    _ks_address="${2}" \
    _publisher="${3}" \
    _address="${4}" \
    _fingerprint="${5}" \
    _key="${6}" \
    _output_prefix="${7}" \
    _abi="${8}" \
    _bytecode="${9}" \
    _compiler_output="${10}" \
    _msg=() \
    _evm_contract_call_opts=() \
    _evmfs_opts=() \
    _keys=() \
    _keys_amount \
    _keys_amount_call_opts=() \
    _work_dir \
    _output_prefix_basename \
    _uri \
    _uris=()
  _work_dir="${_cache_dir}/receive"
  _output_prefix_basename="$( \
    basename \
      "${_output_prefix}")"
  mkdir \
    -p \
    "${_work_dir}"
  _opts_setup
  if [[ "${_key}" == "" ]] && \
     [[ "${_fingerprint}" == "" ]]; then
    _msg=(
      "no target key or fingerprint"
      "specified, downloading all"
      "available keys."
    )
    _msg_info \
      "${_msg[*]}"
    _keys_amount="$( \
      _keys_amount_get)"
    _msg=(
      "got a total of '${_keys_amount}'"
      "keys for address '${_address}'"
    )
    _msg_info \
      "${_msg[*]}"
    _keys+=( $( \
      seq \
        0 \
        "$(( "${_keys_amount}" - 1))")
    )
  elif [[ "${_key}" != "" ]] && \
       [[ "${_fingerprint}" == "" ]]; then
    _keys+=(
      "${_key}"
    )
  elif [[ "${_fingerprint}" != "" ]] && \
       [[ "${_key}" == "" ]]; then
    _key="$( \
      _key_fingerprint_get \
        "${_fingerprint}")"
    _msg=(
      "got key '${_key}' for"
      "fingerprint '${_fingerprint}'"
    )
    _msg_info \
      "${_msg[*]}"
    _keys+=(
      "${_key}"
    )
  fi
  for _key in "${_keys[@]}"; do
    _msg=(
      "getting publisher '${_publisher}'"
      "key '${_key}' uri for address"
      "'${_address}'."
    )
    _msg_info \
      "${_msg[*]}"
    _uri="$( \
      _uri_key_get \
        "${_key}")"
    _uris+=(
      "${_uri}"
    )
  done
  for _uri \
    in $(seq \
           0 \
           "$(( "${#_uris[@]}" - 1))"); do
    _key_file="${_work_dir}/${_output_prefix_basename}.${_keys[${_uri}]}.asc"
    _key_download \
      "${_uris[${_uri}]}" \
      "${_key_file}"
    _key_files+=(
      "${_key_file}"
    )
  done
  for _key in "${_key_files[@]}"; do
    _key_address_check \
      "${_key}" \
      "${_address}"
  done
}

_abi_get() {
  local \
    _deployments="${1}" \
    _network="${2}" \
    _name="${3}" \
    _version="${4}"
  echo \
    "${_deployments}/${_name}/${_network}/${_version}/${_name}.abi.json"
}

_bytecode_get() {
  local \
    _deployments="${1}" \
    _network="${2}" \
    _name="${3}" \
    _version="${4}"
  echo \
    "${_deployments}/${_name}/${_network}/${_version}/${_name}.bin"
}

_compiler_output_get() {
  local \
    _deployments="${1}" \
    _network="${2}" \
    _name="${3}" \
    _version="${4}"
  echo \
    "${_deployments}/${_name}/${_network}/${_version}/${_name}.json"
}

_key_address_check() {
  local \
    _key="${1}" \
    _address="${2}" \
    _domain \
    _email \
    _fingerprint \
    _user_id \
    _msg=()
  _email="$( \
    gpg-key-info \
      -o \
        "email" \
      "${_key}")"
  _domain="${_email#*@}"
  if [[ "${_address}" != "${_domain}" ]]; then
    _msg=(
      "the target address '${_address}'"
      "does not correspond to domain '${_domain}'"
      "of identifier '${_email}'"
      "for key '${_key}'"
    )
    _msg_error \
      "${_msg[*]}" \
      1
  elif [[ "${_address}" == "${_domain}" ]]; then
    _user_id="$( \
      gpg-key-info \
        -o \
          "email" \
        "${_key}")"
    _fingerprint="$( \
      gpg-key-info \
        -o \
          "fingerprint" \
        "${_key}")"
    _msg=(
      "key '${_key}' identifying"
      "valid user id '${_user_id}'"
      "with fingerprint '${_fingerprint}'"
    )
    _msg_info \
      "${_msg[*]}"
  fi
}

_keys_move() {
  local \
    _output_prefix="${1}" \
    _output_prefix_dirname \
    _msg=()
  _output_prefix_dirname="$( \
    dirname \
      "${_output_prefix}")"
  mv \
    "${_key_files[@]}" \
    "${_output_prefix_dirname}"
  _msg=(
    "keys correctly moved to"
    "'${_output_prefix_dirname}' directory"
  )
  _msg_info \
    "${_msg[*]}"
}

_keys_import() {
  local \
    _gnupg_home="${1}" \
    _gpg_opts=() \
    _key \
    _msg=()
  _msg=(
    "importing keys"
    "'${_key_files[*]}' into"
    "GNUPG keystore at directory"
    "${_gnupg_home}"
  )
  _msg_info \
    "${_msg[*]}"
  mkdir \
    -p \
    "${_gnupg_home}"
  chmod \
    700 \
    "${_gnupg_home}"
  _gpg_opts+=(
    --homedir
      "${_gnupg_home}"
    --import
  )
  for _key in "${_key_files[@]}"; do
    GNUPG_HOME="${_gnupg_home}" \
    cat \
      "${_key}" | \
      gpg \
        "${_gpg_opts[@]}" \
        "${_key}"
  done
}

_evm_openpgp_key_receive() {
  local \
    _ks_address="${1}" \
    _ks_version="${2}" \
    _deployments_dir="${3}" \
    _wallet_name="${4}" \
    _wallet_path="${5}" \
    _wallet_password="${6}" \
    _wallet_seed="${7}" \
    _target_network="${8}" \
    _api_key_path="${9}" \
    _cache_dir="${10}" \
    _input_type="${11}" \
    _key_import="${12}" \
    _gnupg_home="${13}" \
    _target_publisher="${14}" \
    _target_address="${15}" \
    _target_key="${16}" \
    _key_fingerprint="${17}" \
    _output_prefix="${18}" \
    _key_files=() \
    _msg=() \
    _ks_abi \
    _ks_bytecode \
    _ks_compiler_output
  shift \
    18
  _command_args+=(
    "$@"
  )
  if [[ "${_target_publisher}" == "" ]]; then
    _target_publisher="${_target_address}"
  fi
  if [[ "${_target_publisher}" != "${_target_address}" ]]; then
    _msg=(
      "you are not getting '${_target_address}'"
      "self-published key but from"
      "publisher '${_target_publisher}'"
    )
    _msg_warning \
      "${_msg[*]}"
  elif [[ "${_target_publisher}" == "${_target_address}" ]]; then
  _msg=(
    "getting '${_target_address}' self-published"
    "key(s) (safest option)"
  )
  _msg_info \
    "${_msg[*]}"
  fi
  if [[ "${_input_type}" == "fingerprint" ]]; then
    _key_fingerprint="${_target_key}"
    _target_key=""
  fi
  if [[ "${_target_key}" == "" ]] && \
     [[ "${_key_fingerprint}" == "" ]]; then
    _msg=(
      "no target key or fingerprint"
      "specified, downloading all"
      "available keys."
    )
    _download_all="true"
  fi
  _ks_abi="$( \
    _abi_get \
      "${_deployments_dir}" \
      "${_target_network}" \
      "KeyServer" \
      "${_ks_version}")"
  _ks_bytecode="$( \
    _bytecode_get \
      "${_deployments_dir}" \
      "${_target_network}" \
      "KeyServer" \
      "${_ks_version}")"
  _ks_compiler_output="$( \
    _compiler_output_get \
      "${_deployments_dir}" \
      "${_target_network}" \
      "KeyServer" \
      "${_ks_version}")"
  _keys_receive \
    "${_target_network}" \
    "${_ks_address}" \
    "${_target_publisher}" \
    "${_target_address}" \
    "${_key_fingerprint}" \
    "${_target_key}" \
    "${_output_prefix}" \
    "${_ks_abi}" \
    "${_ks_bytecode}" \
    "${_ks_compiler_output}"
  if [[ "${_key_import}" == "y" ]]; then
    _keys_import \
      "${_gnupg_home}"
  elif [[ "${_key_import}" == "n" ]]; then
    _keys_move \
      "${_output_prefix}"
  fi
}

_wallet_path_get() {
  local \
    _path \
    _name
  _name="$( \
    _get \
      "wallet" \
      "name")"
  _path="${HOME}/.config/evm-wallet/${_name}.dat"
  echo \
    "${_path}"
}

_secret_get() {
  local \
    _secret="${1}" \
    _path \
    _name
  _name="$( \
    _get \
      "wallet" \
      "name")"
  _path="${HOME}/.config/evm-wallet/${_name}-${_secret}.txt"
  echo \
    "${_path}"
}

_api_key_auto_detect() {
  local \
    _chain="${1}" \
    _chain_name \
    _key \
    _msg=()
  _key="$( \
    evm-chains-explorers \
      -c \
        "${_chain}" \
      -s \
        'kirsh' \
      get \
        keys)"
  _chain_name="$( \
    evm-chains-info \
      -o \
        "name" \
      "${_chain}")"
  if [[ ! -e "${_key}" ]]; then
    _msg=(
      "Found no provider services"
      "keys for chain '${_chain_name}'."
      "Check available service"
      "providers with \"evm-chains-info"
      "-o explorers '${_chain}'\""
      "and add the relative api key in"
      "'<user_home>/.config/evm-chains-explorers/<service>/default.txt'"
    )
    _msg_info \
      "${_msg[*]}"
  fi
  _set_override \
    "api" \
    "key" \
    "${_key}"
}

_secret_auto_detect() {
  local \
    _secret="${1}" \
    _secret_type="${2}" \
    _dir \
    _key_gen_opts=() \
    _msg=()
  _path="$( \
    _secret_get \
      "${_secret}")"
  _dir="$( \
    dirname \
      "${_path}")"
  if [[ ! -e "${_path}" ]]; then
    _key_gen_opts+=(
      -t
        "${_secret_type}"
    )
    _msg=(
      "generating ${_secret} '${_path}'"
    )
    if [[ "${quiet}" == "n" ]]; then
      _msg_info \
        "${_msg[*]}"
    fi
    mkdir \
      -p \
      "${_dir}"
    chmod \
      700 \
      "${_dir}"
    chmod \
      700 \
      "${_dir}"
    key-gen \
      "${_key_gen_opts[@]}" \
      "${_path}"
    chmod \
      400 \
      "${_path}"
    _msg=(
      "${_secret} '${_path}' successfully generated"
    )
    if [[ "${quiet}" == "n" ]]; then
      _msg_info \
        "${_msg[*]}"
    fi
  fi
  _set_override \
    "wallet" \
    "${_secret}" \
    "${_path}"
}

_deployments_dir_auto_detect() {
  local \
    _user_level \
    _evm_contract_deployments_dir_opts=() \
    _deployments_dir \
    _system_deployments
  _user_level="$( \
    _get \
      "user" \
      "level")"
  if [[ "${_user_level}" == "y" ]]; then
    _evm_contract_deployments_dir_opts+=(
      -u
    )
  fi
  _deployments_dir="$( \
    evm-contract-deployments-dir \
      "${_evm_contract_deployments_dir_opts[@]}" \
      "evm-openpgp-keyserver")"
  if [[ ! -d "${_deployments_dir}" ]]; then
    _system_deployments="$( \
     evm-contract-deployments-dir \
       "evm-openpgp-keyserver")"
    _msg=(
      "user deployments directory"
      "'${_deployments_dir}' does"
      "not exists, importing system deployments"
      "directory '${_system_deployments}'"
    )
    _msg_info \
      "${_msg[*]}"
    mkdir \
      -p \
      "${_deployments_dir}"
    chmod \
      700 \
      "${_deployments_dir}"
    cp \
     -r \
     "${_system_deployments}/"* \
     "${_deployments_dir}"
  fi
  _set_override \
    "deployments" \
    "dir" \
    "${_deployments_dir}"
}

_network_auto_detect() {
  local \
    _contract \
    _contract_deployment \
    _deployments \
    _user \
    _msg=()
  _contract="KeyServer"
  _deployments="$( \
    _get \
      "deployments" \
      "dir")"
  _contract_deployment="${_deployments}/${_contract}"
  _user="$( \
    _get \
      "user" \
      "level")"
  if [[ "${_user}" == "y" ]]; then
    _msg=(
     "User deployments enabled, looking"
     "for cheapest network deployments at" 
     "path '${_contract_deployment}'"
   )
   _msg_info \
     "${_msg[*]}"
  fi
  _network="$( \
    evm-contract-deployment-networks \
      -C \
      "${_contract_deployment}")"
  if [[ "${_user}" == "y" ]]; then
    _msg=(
      "Found network '${_network}'"
    )
    _msg_info \
      "${_msg[*]}"
  fi
  _set_override \
    "target" \
    "network" \
    "${_network}"
}

_ks_version_auto_detect() {
  local \
    _config \
    _contract \
    _deployments \
    _network \
    _version
  _contract="KeyServer"
  _deployments="$( \
    _get \
      "deployments" \
      "dir")"
  _network="$( \
    _get \
      "target" \
      "network")"
  _config="${_deployments}/${_contract}/${_network}/config.sh"
  _version="$( \
    evm-contract-deployment-versions \
      -H \
      "${_config}")"
  _set_override \
    "ks" \
    "version" \
    "${_version}"
}

_ks_address_auto_detect() {
  local \
    _address \
    _contract \
    _network \
    _deployments \
    _user \
    _version \
    _evm_contract_deployment_address_opts=() \
    _msg=()
  _contract="KeyServer"
  _network="$( \
    _get \
      "target" \
      "network")"
  _evm_contract_deployment_address_opts+=(
    -n
      "${_network}"
  )
  _version="$( \
    _get \
      "ks" \
      "version")"
  if [[ "${_version}" != "" ]]; then
    _evm_contract_deployment_address_opts+=(
      -V
        "${_version}"
    )
  fi
  _user="$( \
    _get \
      "user" \
      "level")"
  if [[ "${_user}" == "n" ]]; then
    _evm_contract_deployment_address_opts+=(
      -a
        "evm-openpgp-keyserver"
    )
  elif [[ "${_user}" == "y" ]]; then
    _deployments="$( \
      _get \
        "deployments" \
        "dir")"
    _evm_contract_deployment_address_opts+=(
      -u
      -d
        "${_deployments}" 
    )
  fi
  _address="$( \
    evm-contract-deployment-address \
      "${_evm_contract_deployment_address_opts[@]}" \
      "${_contract}")"
  if [[ "${_address}" == "" ]]; then
    _msg=(
      "error getting KeyServer version"
      "${_version} deployment address"
      "for network '${_network}'"
    )
    _msg_error \
      "${_msg[*]}" \
      1
  fi
  _set_override \
    "ks" \
    "address" \
    "${_address}"
}

_input_type_auto_detect() {
  local \
    _target_key \
    _input_type \
    _re
  _re='^[0-9]+$'
  _target_key="$( \
    _get \
      "target" \
      "key")"
  _input_type="number"
  if [[ "${_target_key}" != "" ]]; then
    if ! [[ ${_target_key} =~ ${_re} ]] ; then
      _input_type="fingerprint"
    fi
  fi
  _set_override \
    "input" \
    "type" \
    "${_input_type}"
}

_key_import_auto_detect() {
  local \
    _gnupg_home \
    _import
  _gnupg_home="$( \
    _get \
      "gnupg" \
      "home")"
  _import="y"
  if [[ "${_gnupg_home}" == "${HOME}/.gnupg" ]]; then
    _import="n"
  fi
  _set_override \
    "key" \
    "import" \
    "${_import}"
}

_output_prefix_auto_detect() {
  local \
    _key_import \
    _base_prefix \
    _key_basename \
    _output_prefix \
    _target_address
  _key_import="$( \
    _get \
      "key" \
      "import")"
  _target_address="$( \
    _get \
      "target" \
      "address")"
  _target_key="$( \
    _get \
      "target" \
      "key")"
  _output_prefix=""
  if [[ "${_key_import}" == "n" ]]; then
    _base_prefix="$( \
      pwd)"
  elif [[ "${_key_import}" == "y" ]]; then
    _base_prefix="${HOME}/.cache/evm-openpgp-keyserver/receive"
  fi
  if [[ "${_target_address}" != "" ]]; then
    if [[ "${_target_key}" != "" ]]; then
      _key_basename="${_target_address}.${_target_key}"
    elif [[ "${_target_key}" == "" ]]; then
      _key_basename="${_target_address}"
    fi
  elif [[ "${_target_address}" == "" ]]; then
    _key_basename="<target_address>.<target_key>.key"
  fi
  _output_prefix="${_base_prefix}/${_key_basename}"
  _set_override \
    "output" \
    "prefix" \
    "${_output_prefix}"
}

_set_overrides() {
  local \
    _target_address \
    _target_key
  _target_address="$( \
    _get \
      "target" \
      "address")"
  _target_key="$( \
    _get \
      "target" \
      "key")"
  if [[ -v override_quiet ]]; then
    quiet="${override_quiet}"
  elif [[ -z "${quiet}" ]]; then
    quiet="y"
  fi
  if [[ -v override_color ]]; then
    color="${override_color}"
  elif [[ -z "${color}" ]]; then
    color="n"
  fi
  _set_override \
    "receive" \
    "date" \
    "$(_get_date_human)"
  _set_override \
    "wallet" \
    "name" \
    "default"
  _set_override \
    "user" \
    "level" \
    "n"
  _deployments_dir_auto_detect
  _network_auto_detect
  _api_key_auto_detect \
    "$(_get \
         "target" \
         "network")"
  _set_override \
    "wallet" \
    "path" \
    "$(_wallet_path_get)"
  _secret_auto_detect \
    "seed" \
    "seed"
  _secret_auto_detect \
    "password" \
    "plain"
  _set_override \
    "wallet" \
    "address" \
    "$(evm-wallet \
         get \
           "${wallet_name}" \
           "address")"
  _set_override \
    "cache" \
    "dir" \
    "$(_cache_dir_auto_detect)"
  _ks_version_auto_detect
  _ks_address_auto_detect
  _set_override \
    "gnupg" \
    "home" \
    "${HOME}/.gnupg"
  _key_import_auto_detect
  _set_override \
    "target" \
    "publisher" \
    "${_target_address}"
  _input_type_auto_detect
  _output_prefix_auto_detect
}

# Show help usage, with an exit status.
# $1: exit status number.
_usage() {
  local \
    _exit="${1}" \
    _contract \
    _ks_deployment \
    _networks \
    _usage_text
  _contract="KeyServer"
  _ks_deployment="$( \
    _get \
      "deployments" \
      "dir")/${_contract}"
  _networks="$( \
    evm-contract-deployment-networks \
      -A \
      "${_ks_deployment}")"
  IFS='' \
    read \
      -r \
      -d '' \
      _usage_text << \
        ENDUSAGETEXT || true
Ethereum Virtual Machine-compatible network OpenPGP Key Server keys receiver

Usage:
  $(_get "app" "name")
    [options]
    <key>

  networks:
$(_display_networks \
     "${_networks[*]}")

  options:
     -A <ks_address>        Address of the EVM OpenPGP Key Server
                            on the network.
                            Default: ${ks_address}
     -V <ks_version>        Version of the target EVM OpenPGP Key
                            Server.
                            Default: ${ks_version}
     -u                     Whether to retrieve key server
                            address from user directory or from
                            a custom deployment.
                            Default: ${user_level}
     -d <deployments_dir>   Contracts deployments directory.
                            Default: ${deployments_dir}
     -N <wallet_name>       Wallet name.
                            Default: ${wallet_name}
     -w <wallet_path>       Wallet path.
                            Default: ${wallet_path}
     -p <wallet_password>   Wallet password.
                            Default: ${wallet_password}
     -s <wallet_seed>       Wallet seed path.
                            Default: ${wallet_seed}
     -n <network>           EVM network name (${_networks[*]}).
                            Default: ${target_network}
     -k <api_key>           Etherscan-like service key.
                            Default: ${api_key}
     -P <publisher>         Key publisher.
                            Default: ${target_publisher}

     -H <gnupg_home>        GnuPG configuration directory.
                            Default: ${gnupg_home}
     -t <input_type>        It can be 'fingerprint' or
                            'number'.
                            Default: ${input_type}
     -f <y/n>               Save the keys to file without
                            importing them into the keystore.
                            Defaults to 'y' if the GNUPG
                            configuration directory
                            is not the default user one,
                            'n' otherwise.
                            Default: ${key_import}
     -o                     Output key prefix.
                            Default: ${output_prefix}
     -C <cache_dir>         Work directory
                            Default: ${cache_dir}

     -h                     This message.
     -c                     Enable color output
     -v                     Enable verbose output
ENDUSAGETEXT
  _printf \
    '%s\n' \
    "${_usage_text}"
  exit \
    "${_exit}"
}

_display_flags() {
  local \
    _flag \
    _flags=(
      "${1}"
    )
  for _flag \
    in "${_flags[@]}"; do
  _msg_info \
    "                             ${_flag}"
  done
}

_display_networks() {
  local \
    _network \
    _network_name \
    _networks=(
      "${1}"
    )
  for _network \
    in "${_networks[@]}"; do
    _network_name="$( \
      evm-chains-info \
        -i \
          "id" \
        -o \
          "name" \
        "${_network}")"
  echo \
    "    ${_network_name}"
  done
}

# Shows configuration options.
_show_config() {
  _msg_info "${app_name} configuration"
  _msg_info "             Receive date:   ${receive_date}"
  _msg_info "       Key server address:   ${ks_address}"
  _msg_info "       Key server version:   ${ks_version}"
  _msg_info "               User level:   ${user_level}"
  _msg_info "    Deployments directory:   ${deployments_dir}"
  _msg_info "                Publisher:   ${wallet_address}"
  _msg_info "              Wallet name:   ${wallet_name}"
  _msg_info "              Wallet path:   ${wallet_path}"
  _msg_info "          Wallet password:   ${wallet_password}"
  _msg_info "              Wallet seed:   ${wallet_seed}"
  _msg_info "           Target network:   ${target_network}"
  _msg_info "                  API key:   ${api_key}"
  _msg_info "          Cache directory:   ${cache_dir}"
  _msg_info "               Input type:   ${input_type}"
  _msg_info "               Import key:   ${key_import}"
  _msg_info "     GnuPG home directory:   ${gnupg_home}"
  _msg_info "         Target publisher:   ${target_publisher}"
  _msg_info "           Target address:   ${target_address}"
  _msg_info "               Target key:   ${target_key}"
  _msg_info "          Key fingerprint:   ${key_fingerprint}"
  _msg_info "        Output key prefix:   ${output_prefix}"
}

_globals
_global_variables
_requirements
_config_user_init \
  "$(_get \
       "app" \
       "name")"
# shellcheck disable=SC2034
while \
  getopts \
    'A:V:ud:N:w:p:s:n:k:H:t:f:C:P:cvh?' \
    arg; do
  case \
    "${arg}" in
    A) override_ks_address="${OPTARG}" ;;
    V) override_ks_version="${OPTARG}" ;;
    u) override_user_level="y" ;;
    d) override_deployments_dir="${OPTARG}" ;;
    N) override_wallet_name="${OPTARG}" ;;
    w) override_wallet_path="${OPTARG}" ;;
    p) override_wallet_password="${OPTARG}" ;;
    s) override_wallet_seed="${OPTARG}" ;;
    n) override_target_network="${OPTARG}" ;;
    k) override_api_key="${OPTARG}" ;;
    H) override_gnupg_home="${OPTARG}" ;;
    t) override_input_type="${OPTARG}" ;;
    f) override_key_import="${OPTARG}" ;;
    C) override_cache_dir="${OPTARG}" ;;
    P) override_target_publisher="${OPTARG}" ;;
    c) override_color="y" ;;
    v) override_quiet="n" ;;
    h|?) _set_overrides && \
         _usage \
           0 ;;
    *)
    _msg_error \
      "Invalid argument '${arg}'" \
      0
    _usage \
      1
    ;;
  esac
done
shift \
  $(( \
    OPTIND - 1 \
  ))
if (( $# < 1 )); then
  _msg_error \
    "no target address given" \
    0
  _set_overrides
  _usage \
    1
fi
if (( 0 < $# )); then
  _set \
    "target" \
    "address" \
    "${1}"
fi
if (( $# < 2 )); then
  _msg=(
    "no target key given,"
    "getting all of them."
  )
  _msg_warning \
    "${_msg[*]}"
fi
if (( 1 < $# )); then
  _set \
    "target" \
    "key" \
    "${2}"
fi
shift \
  2 || \
  true
command_args+=(
  "$@"
)
_set_overrides
_show_config
app_opts=(
  "${ks_address}"
  "${ks_version}"
  "${deployments_dir}"
  "${wallet_name}"
  "${wallet_path}"
  "${wallet_password}"
  "${wallet_seed}"
  "${target_network}"
  "${api_key}"
  "${cache_dir}"
  "${input_type}"
  "${key_import}"
  "${gnupg_home}"
  "${target_publisher}"
  "${target_address}"
  "${target_key}"
  "${key_fingerprint}"
  "${output_prefix}"
)
_evm_openpgp_key_receive \
  "${app_opts[@]}"

# vim:set sw=2 sts=-1 et:
